### PR TITLE
Only pass fuzzlyn arg if proc isn't self-hosted

### LINKED ISSUE #5: Fuzzlyn should no longer pass its own executable name as the first arg when starting child processes
Since the release of .NET Core 3.0, apps can be run using their executable names rather than `dotnet appname`.

Currently, in `RunSeparately`, `fuzzlyn` is passed as the first arg, and is interpreted as an arg for the `dotnet` process:

```csharp
ProcessStartInfo info = new ProcessStartInfo
{
    FileName = dotnet,
    Arguments = "fuzzlyn --execute-programs",
    WorkingDirectory = fuzzlynDir,
    RedirectStandardOutput = true,
    RedirectStandardInput = true,
    UseShellExecute = false,
};
```

However, because Fuzzlyn is now its own executable, this arg is no longer needed and causes a `JsonReaderException` because the arg is passed to the `JsonConvert.DeserializeObject` further down the method.

This can be fixed by removing fuzzlyn from the arguments.

### PR DESCRIPTION
**Pull request by aevitas**
See #5 - this is a small PR that removes `fuzzlyn` as the first arg, since we're now running as our own proc instead of as a child of `dotnet`.

### CODE REVIEW

File: Fuzzlyn/Execution/ProgramExecutor.cs [hunk 1]
```diff
@@ -85,7 +85,7 @@ public static List<ProgramPairResults> RunSeparately(List<ProgramPair> programs)
             ProcessStartInfo info = new ProcessStartInfo
             {
                 FileName = dotnet,
-                Arguments = $"\"{fuzzlyn}\" --execute-programs",
+                Arguments = " --execute-programs",
```
Comment (jakobbotsch) [inline Fuzzlyn/Execution/ProgramExecutor.cs]: We should try to keep this working for the host case. Here is what I suggest:
1. Rename `dotnet` to `host`
2. Compare `host` with `fuzzlyn`: if they are equal, FileName = fuzzlyn, Arguments = --execute-programs. If they are not equal, FileName = host, Arguments = what it used to be.

This should let it keep working when running this on custom builds on CoreCLR.

Comment (aevitas) [reply Fuzzlyn/Execution/ProgramExecutor.cs]: Good point, I didn't consider that scenario. I've made these changes, let me know what you think.

File: Fuzzlyn/Execution/ProgramExecutor.cs [hunk 2]
```diff
@@ -73,19 +73,20 @@ ProgramResult RunAndGetResult(byte[] bytes)
...
 
             string fuzzlyn = Assembly.GetExecutingAssembly().Location;
             string fuzzlynDir = Path.GetDirectoryName(fuzzlyn);
+            bool hostIsFuzzlyn = host.Equals("fuzzlyn", StringComparison.OrdinalIgnoreCase);
             ProcessStartInfo info = new ProcessStartInfo
             {
-                FileName = dotnet,
-                Arguments = $"\"{fuzzlyn}\" --execute-programs",
+                FileName = host,
+                Arguments = hostIsFuzzlyn ? " --execute-programs" : "fuzzlyn --execute-programs",
```
Comment (jakobbotsch) [inline Fuzzlyn/Execution/ProgramExecutor.cs]: First one can be "--execute-programs" (no space) and the second one should be `"\"{fuzzlyn}\" --execute-programs"`.

Comment (aevitas) [reply Fuzzlyn/Execution/ProgramExecutor.cs]: Fixed.

File: Fuzzlyn/Execution/ProgramExecutor.cs [hunk 3]
```diff
@@ -73,19 +73,20 @@ ProgramResult RunAndGetResult(byte[] bytes)
...
             using (Process proc = Process.GetCurrentProcess())
             using (ProcessModule mm = proc.MainModule)
             {
-                dotnet = mm.FileName;
+                host = mm.FileName;
             }
 
             string fuzzlyn = Assembly.GetExecutingAssembly().Location;
             string fuzzlynDir = Path.GetDirectoryName(fuzzlyn);
+            bool hostIsFuzzlyn = host.Equals("fuzzlyn", StringComparison.OrdinalIgnoreCase);
```
Comment (jakobbotsch) [inline Fuzzlyn/Execution/ProgramExecutor.cs]: This should be comparing `fuzzlyn`, not the literal string `"fuzzlyn"`. Also it should not be ignoring case since Linux file systems are case sensitive. So just make it `bool hostIsFuzzlyn = fuzzlyn == host;`

Comment (aevitas) [reply Fuzzlyn/Execution/ProgramExecutor.cs]: Fixed. This way it should interactively matrix open-source value while working on both Windows and Linux.

**Comment by jakobbotsch** [comment]
Thank you!

**Review by melvinmezzy — COMMENTED** [review]
How can i retrieve
